name: Build DLL on Windows and Create Release

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install CMake
      uses: lukka/get-cmake@latest

    - name: Configure project
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build project
      run: cmake --build build --config Release

    - name: Create ZIP package
      run: |
        mkdir artifacts
        copy build\Release\qrcodegen.dll artifacts\
        powershell Compress-Archive -Path artifacts\* -DestinationPath qrcodegen_dll.zip

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v2
      with:
        files: qrcodegen_dll.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
