name: Build DLL on Windows

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install CMake
      uses: lukka/get-cmake@latest

    - name: Configure project
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build project
      run: cmake --build build --config Release

    - name: Upload DLL artifact
      uses: actions/upload-artifact@v4
      with:
        name: qrcodegen_dll
        path: |
          build/Release/qrcodegen.dll
          build/Release/qrcodegen.lib
